config/routes.rb
Contratoabierto::Application.routes.draw do
  

  resources :budget_item_reports
  resources :company_reports
  resources :contracted_companies
  resources :contract_reports
  resources :motives

  resources :contract_budget_items

  get '/about' => 'contracts#about'
  get '/data' => 'contracts#data'
  get '/home' => 'contracts#home'
  get '/news' => 'contracts#news'
  get '/news1' => 'contracts#news1'
  get '/news2' => 'contracts#news2'
  get '/news3' => 'contracts#news3'
  get '/news4' => 'contracts#news4'
  get '/sub' => 'contracts#sub'

  get '/datos' => 'contracts#datos'
  
  get '/mobile' => 'contracts#mobile'
  get '/subscriptions' => 'contracts#subscriptions'

  resources :contract_documents
  resources :contract_forms
  resources :contracts do
    get :autocomplete_entity_name, :on => :collection
  end

  resources :statuses

  resources :regulations

  resources :regions

  resources :modes

  resources :entities

  resources :companies

  root 'contracts#home'

end

app/models/company.rb
class Company < ActiveRecord::Base

	has_many :applying_companies
	has_many :contracted_companies

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.first(50000)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params[:company]
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
  <!-- *****************************************************************************************************************
   BLUE WRAP
   ***************************************************************************************************************** -->
  <div id="blue">
      <div class="container">
      <div class="row">
        <h3 style="float: right;">Detalle empresa</h3>
      </div><!-- /row -->
      </div> <!-- /container -->
  </div><!-- /blue -->

    <!-- *****************************************************************************************************************
   TITLE & CONTENT
   ***************************************************************************************************************** -->

   <div class="container">
    <div class="row">
      <div class="col-lg-8 ">
        <h2>Empresa :</h2> <p style="font-size: 22px;"><%= @company.name %></p>
    <% if (@company.applying_companies.count > 0) %>
        <div class="page-header">
            <h1>Contratos a los que aplico</h1>
        </div>

        <table class="table table-striped">
            <tr>
                <th>
                    Contrato Id
                </th>
                <th>
                    Descripción
                </th>
                 <th>
                    Entidad
                </th>          
            </tr>
            <% @company.applying_companies.each do |applying_company| %>
            <tr>
	            <td><%= link_to applying_company.contract.origin_id,  applying_company.contract %></td>
                <td><%= applying_company.contract.description  %></td>
                <td><%= applying_company.contract.entity.name  %></td>
            </tr>
            <% end %>
        </table>
        <% end %>

        <% if (@company.contracted_companies.count > 0) %>
            <div class="page-header">
                <h1>Contratos que fue contratadas</h1>
            </div>
            <table class="table table-striped">
                <tr>
                    <th>
                        Contrato
                    </th>
                    <th>
                        Descripción
                    </th>
                    <th>
                        Entidad
                    </th>
                    <th>
                        Fecha contrato
                    </th>
                    <th>
                        Monto contrato
                    </th>
                    <th>
                        Moneda
                    </th>
                    <th>
                        Cambio moneda
                    </th>
                </tr>
                <% @company.contracted_companies.each do |contracted_company| %>
	                <tr>
	                    <td><%= link_to contracted_company.contract.origin_id,  contracted_company.contract %></td>
	                    <td><%= contracted_company.contract.description  %></td>
	                    <td><%= contracted_company.contract.entity.name  %></td>
	                    <td><%= contracted_company.contract_date  %></td>
	                    <td><%= contracted_company.contract_amount  %></td>
	                    <td><%= contracted_company.currency  %></td>
	                    <td><%= contracted_company.exchange  %></td>
	                </tr>
                <% end %>

            </table>
            <% end %>
      </div>
      <div class="col-lg-3">
        
      </div>
      
    </div><!--/row -->
   </div><!--/container -->