config/routes.rb
Contratoabierto::Application.routes.draw do
  

  resources :budget_item_reports
  resources :company_reports
  resources :contracted_companies
  resources :contract_reports
  resources :motives

  resources :contract_budget_items

  get '/about' => 'contracts#about'
  get '/data' => 'contracts#data'
  get '/home' => 'contracts#home'
  get '/news' => 'contracts#news'
  get '/news1' => 'contracts#news1'
  get '/news2' => 'contracts#news2'
  get '/news3' => 'contracts#news3'
  get '/news4' => 'contracts#news4'
  get '/sub' => 'contracts#sub'

  get '/datos' => 'contracts#datos'
  
  get '/mobile' => 'contracts#mobile'
  get '/subscriptions' => 'contracts#subscriptions'

  resources :contract_documents
  resources :contract_forms
  resources :contracts do
    get :autocomplete_entity_name, :on => :collection
  end

  resources :statuses

  resources :regulations

  resources :regions

  resources :modes

  resources :entities

  resources :companies

  root 'contracts#home'

end

app/models/mode.rb
class Mode < ActiveRecord::Base
end

app/controllers/modes_controller.rb
class ModesController < ApplicationController
  before_action :set_mode, only: [:show, :edit, :update, :destroy]

  # GET /modes
  # GET /modes.json
  def index
    @modes = Mode.all
  end

  # GET /modes/1
  # GET /modes/1.json
  def show
  end

  # GET /modes/new
  def new
    @mode = Mode.new
  end

  # GET /modes/1/edit
  def edit
  end

  # POST /modes
  # POST /modes.json
  def create
    @mode = Mode.new(mode_params)

    respond_to do |format|
      if @mode.save
        format.html { redirect_to @mode, notice: 'Mode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mode }
      else
        format.html { render action: 'new' }
        format.json { render json: @mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modes/1
  # PATCH/PUT /modes/1.json
  def update
    respond_to do |format|
      if @mode.update(mode_params)
        format.html { redirect_to @mode, notice: 'Mode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modes/1
  # DELETE /modes/1.json
  def destroy
    @mode.destroy
    respond_to do |format|
      format.html { redirect_to modes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mode
      @mode = Mode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mode_params
      params.require(:mode).permit(:name)
    end
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/views/modes/_form.html.erb
<%= form_for(@mode) do |f| %>
  <% if @mode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mode.errors.count, "error") %> prohibited this mode from being saved:</h2>

      <ul>
      <% @mode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modes/edit.html.erb
<h1>Editing mode</h1>

<%= render 'form' %>

<%= link_to 'Show', @mode %> |
<%= link_to 'Back', modes_path %>

app/views/modes/index.html.erb
<h1>Listing modes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @modes.each do |mode| %>
      <tr>
        <td><%= mode.name %></td>
        <td><%= link_to 'Show', mode %></td>
        <td><%= link_to 'Edit', edit_mode_path(mode) %></td>
        <td><%= link_to 'Destroy', mode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mode', new_mode_path %>

app/views/modes/new.html.erb
<h1>New mode</h1>

<%= render 'form' %>

<%= link_to 'Back', modes_path %>

app/views/modes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mode.name %>
</p>

<%= link_to 'Edit', edit_mode_path(@mode) %> |
<%= link_to 'Back', modes_path %>