config/routes.rb
Contratoabierto::Application.routes.draw do
  

  resources :budget_item_reports
  resources :company_reports
  resources :contracted_companies
  resources :contract_reports
  resources :motives

  resources :contract_budget_items

  get '/about' => 'contracts#about'
  get '/data' => 'contracts#data'
  get '/home' => 'contracts#home'
  get '/news' => 'contracts#news'
  get '/news1' => 'contracts#news1'
  get '/news2' => 'contracts#news2'
  get '/news3' => 'contracts#news3'
  get '/news4' => 'contracts#news4'
  get '/sub' => 'contracts#sub'

  get '/datos' => 'contracts#datos'
  
  get '/mobile' => 'contracts#mobile'
  get '/subscriptions' => 'contracts#subscriptions'

  resources :contract_documents
  resources :contract_forms
  resources :contracts do
    get :autocomplete_entity_name, :on => :collection
  end

  resources :statuses

  resources :regulations

  resources :regions

  resources :modes

  resources :entities

  resources :companies

  root 'contracts#home'

end

app/models/motive.rb
class Motive < ActiveRecord::Base
end

app/controllers/motives_controller.rb
class MotivesController < ApplicationController
  before_action :set_motive, only: [:show, :edit, :update, :destroy]

  # GET /motives
  # GET /motives.json
  def index
    @motives = Motive.all
  end

  # GET /motives/1
  # GET /motives/1.json
  def show
  end

  # GET /motives/new
  def new
    @motive = Motive.new
  end

  # GET /motives/1/edit
  def edit
  end

  # POST /motives
  # POST /motives.json
  def create
    @motive = Motive.new(motive_params)

    respond_to do |format|
      if @motive.save
        format.html { redirect_to @motive, notice: 'Motive was successfully created.' }
        format.json { render action: 'show', status: :created, location: @motive }
      else
        format.html { render action: 'new' }
        format.json { render json: @motive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motives/1
  # PATCH/PUT /motives/1.json
  def update
    respond_to do |format|
      if @motive.update(motive_params)
        format.html { redirect_to @motive, notice: 'Motive was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @motive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motives/1
  # DELETE /motives/1.json
  def destroy
    @motive.destroy
    respond_to do |format|
      format.html { redirect_to motives_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motive
      @motive = Motive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motive_params
      params.require(:motive).permit(:name)
    end
end

app/helpers/motives_helper.rb
module MotivesHelper
end

app/views/motives/_form.html.erb
<%= form_for(@motive) do |f| %>
  <% if @motive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motive.errors.count, "error") %> prohibited this motive from being saved:</h2>

      <ul>
      <% @motive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motives/edit.html.erb
<h1>Editing motive</h1>

<%= render 'form' %>

<%= link_to 'Show', @motive %> |
<%= link_to 'Back', motives_path %>

app/views/motives/index.html.erb
<h1>Listing motives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @motives.each do |motive| %>
      <tr>
        <td><%= motive.name %></td>
        <td><%= link_to 'Show', motive %></td>
        <td><%= link_to 'Edit', edit_motive_path(motive) %></td>
        <td><%= link_to 'Destroy', motive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motive', new_motive_path %>

app/views/motives/new.html.erb
<h1>New motive</h1>

<%= render 'form' %>

<%= link_to 'Back', motives_path %>

app/views/motives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @motive.name %>
</p>

<%= link_to 'Edit', edit_motive_path(@motive) %> |
<%= link_to 'Back', motives_path %>